### ISSUE TITLE
adb in rust

### ISSUE THREAD

**Issue by dvc94ch** [rust-mobile/xbuild#27]

**Comment by dvc94ch** [comment]
@MarijnS95 do you use adb via tcp or USB? adb-rs seems pretty neat, although we'd have to implement a USB transport

**Comment by MarijnS95** [comment]
@dvc94ch Via USB now, I can probably help with USB transports if you need. I see you have forked `adb-rs` and I'll see if I can help out if you need any.

**Comment by MarijnS95** [comment]
Thanks for closing it. This seems to be something that we might want to have at some point, as long as it plays nicely with concurrent `adb` which is a much larger problem to solve. For that I think it should effectively connect to an existing `adb server` if it is already running, and otherwise open a USB transport itself. But in that case one would want `adb` on the cmdline to connect to our open connection or something... And we're effectively reimplementing the adb server and client in Rust :)

Don't forget to close unfinished/unimplemented things as "not planned" though so that there's no false sense of it being "completed" instead.
